import "./globals.css";
import "../utils/fontawesome";
import { Navbar, Footer } from "../components";

export const metadata = {
  title: "Ekdanta Murtis",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Navbar />
        <main>{children}</main>
      <Footer />
    </html>
  );
}
